# Generated by Django 3.0.3 on 2020-03-25 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FBFileSchedularModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field', models.FileField(upload_to='facebook/')),
                ('url_field', models.URLField(blank=True, default='')),
                ('text_field', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
