# Generated by Django 3.0.3 on 2020-03-27 18:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstaFileSchedular',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field', models.FileField(blank=True, null=True, upload_to='instagram/')),
                ('schedule_time', models.DateTimeField(default=datetime.datetime.now)),
                ('url_field', models.URLField(blank=True, default='')),
                ('text_field', models.CharField(max_length=200)),
            ],
        ),
    ]
