# Generated by Django 3.0.3 on 2020-03-27 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('instagram_photo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instafileschedular',
            name='url_field',
        ),
    ]
