# Generated by Django 3.0.3 on 2020-03-24 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileSchedularModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_field', models.FileField(upload_to='documents/')),
                ('schedule_time', models.DateTimeField()),
            ],
        ),
    ]
