# Generated by Django 3.0.3 on 2020-03-25 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_posting', '0003_remove_fileschedularmodel_schedule_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileschedularmodel',
            name='url_field',
            field=models.URLField(default=''),
        ),
    ]
