# Generated by Django 3.0.3 on 2020-03-25 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_posting', '0004_fileschedularmodel_url_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileschedularmodel',
            name='text_field',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='fileschedularmodel',
            name='url_field',
            field=models.URLField(blank=True, default=''),
        ),
    ]
