# Generated by Django 3.0.3 on 2020-03-26 12:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_posting', '0005_auto_20200325_1026'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileschedularmodel',
            name='schedule_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
