# Generated by Django 3.0.4 on 2020-03-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_posting', '0006_fileschedularmodel_schedule_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileschedularmodel',
            name='file_field',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
