# Generated by Django 3.0.4 on 2020-03-26 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_posting', '0007_auto_20200326_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileschedularmodel',
            name='text_field',
            field=models.CharField(max_length=200),
        ),
    ]
