# Generated by Django 3.0.4 on 2020-03-26 15:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_posting', '0008_auto_20200326_2041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileschedularmodel',
            name='schedule_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
