# Generated by Django 3.0.4 on 2020-03-26 16:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_posting', '0009_auto_20200326_2055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileschedularmodel',
            name='schedule_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
